### ISSUE TITLE
Service/API list with --rfj returns no details

### ISSUE THREAD

**Issue by Morridt** [zosconnect/zowe-cli-zosconnect-plugin#37]
Without --rfj service/api details are returned.  With --rfj just the following and no service/api details.

zowe zosconnect api list --rfj
{
  "success": true,
  "exitCode": 0,
  "message": "",
  "stdout": "",
  "stderr": "",
  "data": {}
}

same with : 
zowe zosconnect api info rewardSaver --rfj

(have not checked any further options)

**Comment by crshnburn** [comment]
Hi,

Thank you for raising the issue, from the output of your list command it appears that there aren't any APIs installed in the server. However this behaviour could be improved so will look at adding a message when the list commands are empty.

Will also ensure the data element is populated for all the commands where appropriate.

**Comment by Morridt** [comment]
Hi Andrew,
Currently on way home from work so will update in morning. The same command without -rjf did return APIs
Darren

**Comment by Morridt** [comment]
Hi Andrew,
Attached screen shot of version, api list, and api list with --rjf.
...Darren
![29-05-2019 6-52-33 AM](https://user-images.githubusercontent.com/48165087/58511908-2336e100-81df-11e9-8890-301b6bc60269.png)

p.s. love your work!

**Comment by crshnburn** [comment]
Hi Darren,

Thanks for the screenshot, I've just published a new daily build so if you're happy to try it out please run `zowe plugins install @zosconnect/zosconnect-zowe-cli@daily` and see what output you get. It should add the object for the info commands and provide a message when the plug-in detects that the server doesn't have any of a specified resource.

Thanks

Andrew

**Comment by Morridt** [comment]
Thanks Andrew,
Just tested latest and all looking good.
 -- pluginName: @zosconnect/zosconnect-zowe-cli
 -- package: @zosconnect/zosconnect-zowe-cli@daily
 -- version: 1.1.0-201905282148.0

regards
Darren
![29-05-2019 7-08-11 AM](https://user-images.githubusercontent.com/48165087/58512563-c63c2a80-81e0-11e9-9934-b623700a0110.png)

**Comment by crshnburn** [comment]
Awesome, I'll close this issue off and these fixes will make their way into `@lts-incremental`.

If you find anything else or have suggestions for enhancements please raise further issues.

Thanks
