### ISSUE TITLE
TypeError: Parameter `auth` is deprecated. Use `username` / `password` instead.

### ISSUE THREAD

**Issue by valeriacarabelli** [zosconnect/zowe-cli-zosconnect-plugin#62]
Hello.
I’m trying the zosconnect-zowe-cli plugin to be able to administer apis/ services
I followed instruction described here:
https://developer.ibm.com/mainframe/2019/04/11/zowe-cli-plug-in-for-z-os-connect-ee/

Unfortunately, when I try to run any commands to z/OS Connect, I always get the following error:
C:\$USER\SOFTWARE\zowe-cli-package-1.13.0>zowe zosconnect api list
**TypeError: Parameter `auth` is deprecated. Use `username` / `password` instead.**

The commands do work from other clients, like a web browser. I attach a .doc with screenshots including 
the relevant information about zowe, node.js , npm and so on.
[ZOWE DOC issue.docx](https://github.com/zosconnect/zowe-cli-zosconnect-plugin/files/4953486/ZOWE.DOC.issue.docx)

**Comment by crshnburn** [comment]
The problem was in one of the dependant modules of this plug-in which has now been resolved. If you reinstall the plugin then is should work as expected. Please comment back here if not, or raise a new issue for any other problems you may find.

**Comment by valeriacarabelli** [comment]
New plugin installed with 'zowe plugins install @zosconnect/zosconnect-zowe-cli' (no need to uninstall - install) . Now it works as expected. Amazing support, thanks a lot.
